import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { UserProvider } from '@auth0/nextjs-auth0/client';

import Topbar from "@/components/shared/Topbar";
import { Sidebar } from "@/components/shared/Sidebar";
import Bottombar from "@/components/shared/Bottombar";

const inter = Inter({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <UserProvider>
                <body className={inter.className}>
                    <Topbar />
                    <main className="flex flex-row">
                        <Sidebar />
                        <section className="main-container">
                            <div className="w-full max-w-4xl">{children}</div>
                        </section>
                    </main>
                    <Bottombar />
                </body>
            </UserProvider>
        </html>
    );
}
